[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
